In [28]:
"""
A Script that plots the proportions of labeled class behaviors that fall within a certain magnitude.
The goal of this experiment is to determine if there is some more
"""

import torch
import time
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from data.swarmset import ContinuingDataset, SwarmDataset
from src.networks.embedding import NoveltyEmbedding
from src.networks.archive import DataAggregationArchive
from src.networks.ensemble import Ensemble
import numpy as np
from scipy import ndimage
import random
from sklearn.manifold import TSNE

def CSVLineToVec(line):
    line_list = line.strip().replace("\n", "").split(",")
    float_list = []
    for i in line_list:
        float_list.append(float(i))
    float_list = np.array(float_list)
    return float_list

sampled_dataset = SwarmDataset("../data/full-mini", rank=0)
data = sampled_dataset

lim = 1000
embeddings = []
classes = [-1 for i in range(lim)]
for i in range(lim):
    image, genome, behavior = sampled_dataset[i][0], sampled_dataset[i][1], sampled_dataset[i][2]
    for j in range(len(behavior)):
        if behavior[j] < 0.0:
            behavior[j] *= -1
    embeddings.append(genome)

OUT = "../data/oracle"
with open(os.path.join(OUT, "original-hand-labeled-classes.txt"), "r") as f:
    lines = f.readlines()
    for line in lines:
        triplet = CSVLineToVec(line)
        classes[int(triplet[0])] = int(triplet[1])

EPSILON = 0.05
total_counts = [0 for i in range(max(classes) + 1)]
count = [0 for i in range(max(classes) + 1)]
for i, vec in enumerate(embeddings):
    total_counts[classes[i]] += 1

    nparr = np.array(vec)
    # if np.linalg.norm(vec) > EPSILON:
    #     count[classes[i]] += 1
    for l in vec:
        if EPSILON > l > -EPSILON:
            print(vec)
            count[classes[i]] += 1
            break

print(total_counts, count)

[-0.81818182 -0.55555556  0.11111111  0.01010101]
[ 0.13131313  0.91919192 -0.7979798   0.03030303]
[ 0.35353535 -0.01010101  0.71717172  0.6969697 ]
[-0.17171717 -0.21212121 -0.03030303 -0.63636364]
[-0.87878788  0.01010101 -0.01010101  0.85858586]
[ 0.43434343 -0.39393939  0.01010101  0.07070707]
[-0.03030303 -0.75757576 -0.81818182 -0.53535354]
[-0.77777778 -0.67676768  0.43434343 -0.03030303]
[-0.01010101 -0.19191919 -0.85858586  0.01010101]
[-0.13131313 -0.43434343  0.87878788 -0.01010101]
[-0.85858586  0.01010101  0.93939394  0.45454545]
[-0.91919192  0.01010101  0.43434343  0.33333333]
[-0.75757576 -0.33333333  0.85858586 -0.03030303]
[-0.5959596  -0.01010101 -0.09090909 -0.03030303]
[ 0.01010101  0.19191919 -0.73737374 -0.6969697 ]
[-0.01010101 -0.41414141  0.53535354 -0.5959596 ]
[-0.73737374 -0.05050505  0.23232323 -0.03030303]
[ 0.15151515 -0.15151515 -0.03030303  0.47474747]
[ 0.23232323  0.71717172 -0.01010101  0.17171717]
[ 0.11111111 -0.01010101  0.35353535 -0.33333333]
